# SP-IaC-Demo Github Actions
name: Apply and Destroy Actions

on:
  repository_dispatch:

jobs:
  plan:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    # env:
    #   # for terraform HTTP requests to Azure ARM services with required ARM_ prefix
    #   ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
    #   ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
    #   ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
    #   ARM_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destory
        id: destroy
        run: terraform destroy

      # - name: Terraform Plan
      #   run: terraform plan -var-file=config.tfvars
      #   continue-on-error: true

      # - name: Uncolored Terraform Plan for Bot
      #   id: plan
      #   run: terraform plan -no-color -var-file=config.tfvars
      #   continue-on-error: true

      # - name: Terraform PR commands Info
      #   uses: actions/github-script@v4
      #   env:
      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"